apiVersion: argoproj.io/v1alpha1
kind: Application

metadata:
  name: venu-app
  namespace: argocd

spec:

  project: default

  source:
    repoURL: https://github.com/venugh8899/venu-gitops.git
    targetRevision: main
    path: .

  destination:
    server: https://kubernetes.default.svc
    namespace: venu-app

  syncPolicy:
    automated:
      prune: true
      selfHeal: true

    syncOptions:
      - CreateNamespace=true
